# Generated by Django 6.0.3 on 2026-04-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mrp_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
    ]
