# Generated by Django 6.0.3 on 2026-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='men', max_length=20)),
                ('cloth_type', models.CharField(choices=[('shirt', 'Shirt'), ('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('dress', 'Dress'), ('kurta', 'Kurta')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double XL')], default='M', max_length=10)),
                ('fabric', models.CharField(max_length=100)),
                ('fit_type', models.CharField(default='Regular Fit', max_length=50)),
                ('sleeve_type', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='clothing/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='clothing/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='clothing/')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
